### ISSUE TITLE
mark or remove deprecated messages

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-protobuf#41]
There are some deprecated messages in the repo and we should either mark them as deprecated in the doc or remove them.

At the moment the following messages are identified as deprecated:
5.1.59. SetUserLayout
5.1.60. SetUserLayoutAck
5.1.61. SetUserPreferences
5.1.62. SetUserPreferencesAck
5.1.55. SetRegionRequirements

**Comment by veggiesaurus** [comment]
@confluence can you remove these messages? They aren't used in backend or frontend repos

**Comment by confluence** [comment]
Can we defer this until after the mipmaps branch is merged? Otherwise I will have to renumber the versions in three places. Unless it would make sense to piggyback off the mipmaps branch and make all these breaking changes in one major version number. I don't think there's any reason to make one change per number increment.

**Comment by veggiesaurus** [comment]
I'm fine with making all the breaking changes in one version 👍

**Comment by confluence** [comment]
OK, this should be fixed in #40.

**Comment by confluence** [comment]
These changes were already merged in ICD version 18.0.0, and this should be closed.
